image:
  file: .gitpod/Dockerfile

tasks:
  - name: Setup workspace
    command: |
      sudo apt update -q
      sudo apt upgrade -yq
      sudo apt install -yq libgtk-3-dev lua5.1 lua-lgi

vscode:
  extensions:
    - sumneko.lua