image:
  file: .gitpod/Dockerfile

tasks:
  - name: Setup workspace
    command: |
      sudo apt update -q
      sudo apt upgrade -yq
      sudo apt install -yq ccls libgtk-3-dev python3-pip
      sudo pip3 install -Uq meson ninja
      meson _B
      ln -s _B/compile_commands.json

vscode:
  extensions:
    - mesonbuild.mesonbuild
    - ccls-project.ccls